// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admins.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAdmin = `-- name: AddAdmin :exec
INSERT INTO public.admins (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) AddAdmin(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, addAdmin, userID)
	return err
}

const isAdmin = `-- name: IsAdmin :one
SELECT EXISTS (
    SELECT 1 FROM public.admins WHERE user_id = $1
) AS is_admin
`

func (q *Queries) IsAdmin(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isAdmin, userID)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const removeAdmin = `-- name: RemoveAdmin :exec
DELETE FROM public.admins WHERE user_id = $1
`

func (q *Queries) RemoveAdmin(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeAdmin, userID)
	return err
}
