// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_log.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEmailLog = `-- name: InsertEmailLog :exec
INSERT INTO public.email_log (notification_id, to_email_hash, provider, provider_message_id, status, error)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertEmailLogParams struct {
	NotificationID    pgtype.UUID `json:"notification_id"`
	ToEmailHash       []byte      `json:"to_email_hash"`
	Provider          string      `json:"provider"`
	ProviderMessageID *string     `json:"provider_message_id"`
	Status            string      `json:"status"`
	Error             *string     `json:"error"`
}

func (q *Queries) InsertEmailLog(ctx context.Context, arg InsertEmailLogParams) error {
	_, err := q.db.Exec(ctx, insertEmailLog,
		arg.NotificationID,
		arg.ToEmailHash,
		arg.Provider,
		arg.ProviderMessageID,
		arg.Status,
		arg.Error,
	)
	return err
}

const listEmailLog = `-- name: ListEmailLog :many
SELECT id, notification_id, to_email_hash, provider, provider_message_id, status, error, created_at
FROM public.email_log
WHERE ($3::text IS NULL OR status = $3::text)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListEmailLogParams struct {
	Limit        int32   `json:"limit"`
	Offset       int32   `json:"offset"`
	StatusFilter *string `json:"status_filter"`
}

func (q *Queries) ListEmailLog(ctx context.Context, arg ListEmailLogParams) ([]EmailLog, error) {
	rows, err := q.db.Query(ctx, listEmailLog, arg.Limit, arg.Offset, arg.StatusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailLog{}
	for rows.Next() {
		var i EmailLog
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.ToEmailHash,
			&i.Provider,
			&i.ProviderMessageID,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
