// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EmailLog struct {
	ID                pgtype.UUID        `json:"id"`
	NotificationID    pgtype.UUID        `json:"notification_id"`
	ToEmailHash       []byte             `json:"to_email_hash"`
	Provider          string             `json:"provider"`
	ProviderMessageID *string            `json:"provider_message_id"`
	Status            string             `json:"status"`
	Error             *string            `json:"error"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID            pgtype.UUID        `json:"id"`
	Kind          string             `json:"kind"`
	ToEmail       string             `json:"to_email"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	Attempts      int32              `json:"attempts"`
	LastError     *string            `json:"last_error"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LockedUntil   pgtype.Timestamptz `json:"locked_until"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Subscriber struct {
	ID                    pgtype.UUID        `json:"id"`
	Email                 string             `json:"email"`
	Status                string             `json:"status"`
	ConfirmTokenHash      []byte             `json:"confirm_token_hash"`
	ConfirmTokenExpiresAt pgtype.Timestamptz `json:"confirm_token_expires_at"`
	ConfirmedAt           pgtype.Timestamptz `json:"confirmed_at"`
	UnsubscribedAt        pgtype.Timestamptz `json:"unsubscribed_at"`
	Source                *string            `json:"source"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	UserID                pgtype.UUID        `json:"user_id"`
}
