// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueNotifications = `-- name: ClaimDueNotifications :many
WITH due AS (
    SELECT id
      FROM public.notifications
     WHERE status = 'pending'
       AND next_attempt_at <= now()
       AND (locked_until IS NULL OR locked_until <= now())
     ORDER BY next_attempt_at
     LIMIT $1
     FOR UPDATE SKIP LOCKED
)
UPDATE public.notifications n
   SET status       = 'sending',
       attempts     = n.attempts + 1,
       locked_until = now() + ($2::int * interval '1 second'),
       updated_at   = now()
  FROM due
 WHERE n.id = due.id
RETURNING n.id, n.kind, n.to_email, n.payload, n.attempts
`

type ClaimDueNotificationsParams struct {
	Limit        int32 `json:"limit"`
	LeaseSeconds int32 `json:"lease_seconds"`
}

type ClaimDueNotificationsRow struct {
	ID       pgtype.UUID `json:"id"`
	Kind     string      `json:"kind"`
	ToEmail  string      `json:"to_email"`
	Payload  []byte      `json:"payload"`
	Attempts int32       `json:"attempts"`
}

// Workers call this with FOR UPDATE SKIP LOCKED so multiple workers do not
// claim the same row. The same UPDATE flips the row to 'sending' and grants
// a short lease so a crashed worker's row becomes available again.
func (q *Queries) ClaimDueNotifications(ctx context.Context, arg ClaimDueNotificationsParams) ([]ClaimDueNotificationsRow, error) {
	rows, err := q.db.Query(ctx, claimDueNotifications, arg.Limit, arg.LeaseSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueNotificationsRow{}
	for rows.Next() {
		var i ClaimDueNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ToEmail,
			&i.Payload,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countNotifications = `-- name: CountNotifications :one
SELECT count(*)::bigint AS total
FROM public.notifications
WHERE ($1::text IS NULL OR status = $1::text)
`

func (q *Queries) CountNotifications(ctx context.Context, statusFilter *string) (int64, error) {
	row := q.db.QueryRow(ctx, countNotifications, statusFilter)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countSendsLastDay = `-- name: CountSendsLastDay :one
SELECT count(*)::bigint AS total
FROM public.notifications
WHERE status = 'sent'
  AND updated_at > now() - interval '1 day'
`

// Global daily send-cap counter used by the worker to refuse outbound sends
// when we have already sent a configured number of messages in the last 24h.
func (q *Queries) CountSendsLastDay(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSendsLastDay)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const enqueueNotification = `-- name: EnqueueNotification :one
INSERT INTO public.notifications (kind, to_email, payload)
VALUES ($1, $2, $3)
RETURNING id
`

type EnqueueNotificationParams struct {
	Kind    string `json:"kind"`
	ToEmail string `json:"to_email"`
	Payload []byte `json:"payload"`
}

func (q *Queries) EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, enqueueNotification, arg.Kind, arg.ToEmail, arg.Payload)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const hasRecentNotificationForEmail = `-- name: HasRecentNotificationForEmail :one
SELECT EXISTS (
    SELECT 1 FROM public.notifications
     WHERE to_email = $1
       AND kind = $2
       AND created_at > now() - ($3::int * interval '1 second')
       AND status IN ('pending','sending','sent')
) AS recent
`

type HasRecentNotificationForEmailParams struct {
	ToEmail       string `json:"to_email"`
	Kind          string `json:"kind"`
	WindowSeconds int32  `json:"window_seconds"`
}

// Per-email throttle. Returns true if a notification of the same kind for the
// same recipient was created within the supplied window. Used to prevent
// list-bombing via the public subscribe endpoint.
func (q *Queries) HasRecentNotificationForEmail(ctx context.Context, arg HasRecentNotificationForEmailParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasRecentNotificationForEmail, arg.ToEmail, arg.Kind, arg.WindowSeconds)
	var recent bool
	err := row.Scan(&recent)
	return recent, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, kind, to_email, status, attempts, last_error, next_attempt_at, created_at
FROM public.notifications
WHERE ($3::text IS NULL OR status = $3::text)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListNotificationsParams struct {
	Limit        int32   `json:"limit"`
	Offset       int32   `json:"offset"`
	StatusFilter *string `json:"status_filter"`
}

type ListNotificationsRow struct {
	ID            pgtype.UUID        `json:"id"`
	Kind          string             `json:"kind"`
	ToEmail       string             `json:"to_email"`
	Status        string             `json:"status"`
	Attempts      int32              `json:"attempts"`
	LastError     *string            `json:"last_error"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.Limit, arg.Offset, arg.StatusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsRow{}
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ToEmail,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationDead = `-- name: MarkNotificationDead :exec
UPDATE public.notifications
   SET status       = 'dead',
       locked_until = NULL,
       last_error   = $2,
       updated_at   = now()
 WHERE id = $1
`

type MarkNotificationDeadParams struct {
	ID        pgtype.UUID `json:"id"`
	LastError *string     `json:"last_error"`
}

func (q *Queries) MarkNotificationDead(ctx context.Context, arg MarkNotificationDeadParams) error {
	_, err := q.db.Exec(ctx, markNotificationDead, arg.ID, arg.LastError)
	return err
}

const markNotificationFailed = `-- name: MarkNotificationFailed :exec
UPDATE public.notifications
   SET status       = 'failed',
       locked_until = NULL,
       last_error   = $2,
       updated_at   = now()
 WHERE id = $1
`

type MarkNotificationFailedParams struct {
	ID        pgtype.UUID `json:"id"`
	LastError *string     `json:"last_error"`
}

// Permanent failure for a non-retryable reason (e.g. malformed payload,
// unsupported kind). Distinct from `dead`, which means we exhausted retries.
func (q *Queries) MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationFailed, arg.ID, arg.LastError)
	return err
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
UPDATE public.notifications
   SET status       = 'sent',
       locked_until = NULL,
       last_error   = NULL,
       updated_at   = now()
 WHERE id = $1
`

func (q *Queries) MarkNotificationSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationSent, id)
	return err
}

const scheduleNotificationRetry = `-- name: ScheduleNotificationRetry :exec
UPDATE public.notifications
   SET status          = 'pending',
       next_attempt_at = $2,
       last_error      = $3,
       locked_until    = NULL,
       updated_at      = now()
 WHERE id = $1
`

type ScheduleNotificationRetryParams struct {
	ID            pgtype.UUID        `json:"id"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     *string            `json:"last_error"`
}

func (q *Queries) ScheduleNotificationRetry(ctx context.Context, arg ScheduleNotificationRetryParams) error {
	_, err := q.db.Exec(ctx, scheduleNotificationRetry, arg.ID, arg.NextAttemptAt, arg.LastError)
	return err
}
