// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscribers.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmSubscriberByID = `-- name: ConfirmSubscriberByID :execrows
UPDATE public.subscribers
   SET status                  = 'confirmed',
       confirmed_at            = COALESCE(confirmed_at, now()),
       confirm_token_hash      = NULL,
       confirm_token_expires_at = NULL,
       updated_at              = now()
 WHERE id = $1
   AND status IN ('pending','confirmed')
   AND unsubscribed_at IS NULL
`

// Idempotent: re-confirmation is a no-op once already confirmed.
func (q *Queries) ConfirmSubscriberByID(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, confirmSubscriberByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countSubscribers = `-- name: CountSubscribers :one
SELECT count(*)::bigint AS total
FROM public.subscribers
WHERE ($1::text IS NULL OR status = $1::text)
`

func (q *Queries) CountSubscribers(ctx context.Context, statusFilter *string) (int64, error) {
	row := q.db.QueryRow(ctx, countSubscribers, statusFilter)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getSubscriberByConfirmTokenHash = `-- name: GetSubscriberByConfirmTokenHash :one
SELECT id, email, confirm_token_expires_at
FROM public.subscribers
WHERE confirm_token_hash = $1
  AND status = 'pending'
LIMIT 1
`

type GetSubscriberByConfirmTokenHashRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Email                 string             `json:"email"`
	ConfirmTokenExpiresAt pgtype.Timestamptz `json:"confirm_token_expires_at"`
}

// Indexed lookup used by the confirm flow. Only pending rows match.
func (q *Queries) GetSubscriberByConfirmTokenHash(ctx context.Context, confirmTokenHash []byte) (GetSubscriberByConfirmTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSubscriberByConfirmTokenHash, confirmTokenHash)
	var i GetSubscriberByConfirmTokenHashRow
	err := row.Scan(&i.ID, &i.Email, &i.ConfirmTokenExpiresAt)
	return i, err
}

const getSubscriberByEmail = `-- name: GetSubscriberByEmail :one
SELECT id, email, status, confirm_token_hash, confirm_token_expires_at,
       confirmed_at, unsubscribed_at, source, created_at, updated_at
FROM public.subscribers
WHERE email = $1
`

type GetSubscriberByEmailRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Email                 string             `json:"email"`
	Status                string             `json:"status"`
	ConfirmTokenHash      []byte             `json:"confirm_token_hash"`
	ConfirmTokenExpiresAt pgtype.Timestamptz `json:"confirm_token_expires_at"`
	ConfirmedAt           pgtype.Timestamptz `json:"confirmed_at"`
	UnsubscribedAt        pgtype.Timestamptz `json:"unsubscribed_at"`
	Source                *string            `json:"source"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSubscriberByEmail(ctx context.Context, email string) (GetSubscriberByEmailRow, error) {
	row := q.db.QueryRow(ctx, getSubscriberByEmail, email)
	var i GetSubscriberByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.ConfirmTokenHash,
		&i.ConfirmTokenExpiresAt,
		&i.ConfirmedAt,
		&i.UnsubscribedAt,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriberByID = `-- name: GetSubscriberByID :one
SELECT id, email, status, confirm_token_hash, confirm_token_expires_at,
       confirmed_at, unsubscribed_at, source, created_at, updated_at
FROM public.subscribers
WHERE id = $1
`

type GetSubscriberByIDRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Email                 string             `json:"email"`
	Status                string             `json:"status"`
	ConfirmTokenHash      []byte             `json:"confirm_token_hash"`
	ConfirmTokenExpiresAt pgtype.Timestamptz `json:"confirm_token_expires_at"`
	ConfirmedAt           pgtype.Timestamptz `json:"confirmed_at"`
	UnsubscribedAt        pgtype.Timestamptz `json:"unsubscribed_at"`
	Source                *string            `json:"source"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSubscriberByID(ctx context.Context, id pgtype.UUID) (GetSubscriberByIDRow, error) {
	row := q.db.QueryRow(ctx, getSubscriberByID, id)
	var i GetSubscriberByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.ConfirmTokenHash,
		&i.ConfirmTokenExpiresAt,
		&i.ConfirmedAt,
		&i.UnsubscribedAt,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscribers = `-- name: ListSubscribers :many
SELECT id, email, status, confirmed_at, unsubscribed_at, source, created_at
FROM public.subscribers
WHERE ($3::text IS NULL OR status = $3::text)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSubscribersParams struct {
	Limit        int32   `json:"limit"`
	Offset       int32   `json:"offset"`
	StatusFilter *string `json:"status_filter"`
}

type ListSubscribersRow struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	Status         string             `json:"status"`
	ConfirmedAt    pgtype.Timestamptz `json:"confirmed_at"`
	UnsubscribedAt pgtype.Timestamptz `json:"unsubscribed_at"`
	Source         *string            `json:"source"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSubscribers(ctx context.Context, arg ListSubscribersParams) ([]ListSubscribersRow, error) {
	rows, err := q.db.Query(ctx, listSubscribers, arg.Limit, arg.Offset, arg.StatusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscribersRow{}
	for rows.Next() {
		var i ListSubscribersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Status,
			&i.ConfirmedAt,
			&i.UnsubscribedAt,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsubscribeByID = `-- name: UnsubscribeByID :execrows
UPDATE public.subscribers
   SET status                  = 'unsubscribed',
       unsubscribed_at         = now(),
       confirm_token_hash      = NULL,
       confirm_token_expires_at = NULL,
       updated_at              = now()
 WHERE id = $1
   AND status <> 'unsubscribed'
`

// Idempotent. Unsubscribing wipes any confirm token. The WHERE filter ensures
// already-unsubscribed rows return 0 rows-affected so the caller can detect
// the no-op explicitly.
func (q *Queries) UnsubscribeByID(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, unsubscribeByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPendingSubscriber = `-- name: UpsertPendingSubscriber :one
INSERT INTO public.subscribers (email, status, confirm_token_hash, confirm_token_expires_at, source, user_id)
VALUES ($1, 'pending', $2, $3, $4, $5)
ON CONFLICT (email) DO UPDATE
   SET confirm_token_hash       = EXCLUDED.confirm_token_hash,
       confirm_token_expires_at = EXCLUDED.confirm_token_expires_at,
       source                   = COALESCE(public.subscribers.source, EXCLUDED.source),
       user_id                  = COALESCE(public.subscribers.user_id, EXCLUDED.user_id),
       updated_at               = now()
   WHERE public.subscribers.status = 'pending'
RETURNING id, email, status, confirm_token_hash, confirm_token_expires_at, confirmed_at, unsubscribed_at
`

type UpsertPendingSubscriberParams struct {
	Email                 string             `json:"email"`
	ConfirmTokenHash      []byte             `json:"confirm_token_hash"`
	ConfirmTokenExpiresAt pgtype.Timestamptz `json:"confirm_token_expires_at"`
	Source                *string            `json:"source"`
	UserID                pgtype.UUID        `json:"user_id"`
}

type UpsertPendingSubscriberRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Email                 string             `json:"email"`
	Status                string             `json:"status"`
	ConfirmTokenHash      []byte             `json:"confirm_token_hash"`
	ConfirmTokenExpiresAt pgtype.Timestamptz `json:"confirm_token_expires_at"`
	ConfirmedAt           pgtype.Timestamptz `json:"confirmed_at"`
	UnsubscribedAt        pgtype.Timestamptz `json:"unsubscribed_at"`
}

// Insert a pending row or refresh an existing pending one with a new confirm token.
// Already-confirmed and unsubscribed rows are NOT modified so we cannot leak status
// to the caller via different errors.
func (q *Queries) UpsertPendingSubscriber(ctx context.Context, arg UpsertPendingSubscriberParams) (UpsertPendingSubscriberRow, error) {
	row := q.db.QueryRow(ctx, upsertPendingSubscriber,
		arg.Email,
		arg.ConfirmTokenHash,
		arg.ConfirmTokenExpiresAt,
		arg.Source,
		arg.UserID,
	)
	var i UpsertPendingSubscriberRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.ConfirmTokenHash,
		&i.ConfirmTokenExpiresAt,
		&i.ConfirmedAt,
		&i.UnsubscribedAt,
	)
	return i, err
}
